theme: jekyll-theme-slate
    
<!DOCTYPE html>
<html>
  <head>
  <title> My assignment 1</title>
  </head>
  <nav><a href="http://www.w3school.com.cn">This is a link</a></nav>
<body>
<h1>My Profile</h1>
  <h2>Personal Information</h2>
  <p>My name is Nuozehua Li, Jason is my English name. 
    My student number is S3701549, the email address is S3701549@student.rmit.edu.au.
    I come from JiangSu China, in my hometown, there are many famous scenic spot such as natural caves and bamboo forests. 
    I have been in Melbourne for a year, I graduated from diploma and start my bachelor life now. I can speak Chinese, English, but my English still not very good.
    About my hobby, l like playing games in my free time. I also like listening music when I read books, it can make me relax.</p>
  
  
  
  
  
  
  
  
</body>
</html>
